stages:
  - deploy

before_script:
  - eval $(ssh-agent -s)
  - chmod 600 $SSH_PRIVATE_KEY
  - ssh-add $SSH_PRIVATE_KEY

deploy_staging:
  stage: deploy
  script:
    - ssh ubuntu@$APP_URL -o StrictHostKeyChecking=no
    - eval $(ssh-agent -s)
    - chmod 600 $GITHUB_KEY
    - ssh-add $GITHUB_KEY
    - ls
    - cd convexity-blockchain
    - git pull origin master
    - docker-compose build consumer backend
    - docker-compose up -d
    - exit
  only:
    - master
