stages:
  - deploy

before_script:
  - eval $(ssh-agent -s)
  - chmod 600 $SSH_PRIVATE_KEY
  - ssh-add $SSH_PRIVATE_KEY

deploy_staging:
  stage: deploy
  script:
    - ssh ubuntu@$APP_URL -o StrictHostKeyChecking=no ". ./ssh-restart.sh && ssh-add .ssh/gitlab_permission && cd convexity-blockchain && git pull origin master && docker-compose build consumer backend && docker-compose up -d && exit"
  only:
    - master
