stages:
  - build
  - staging
  - production

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login --username $CONTAINER_REGISTRY_USERNAME --password-stdin $CONTAINER_REGISTRY_PASSWORD $CONTAINER_REGISTRY_URL
    - docker build -t $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG .
    - docker tag $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG $CONTAINER_REGISTRY_URL/$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG
    - docker push $CONTAINER_REGISTRY_URL/$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG
