stages:
  - deploy

before_script:
  - eval $(ssh-agent -s)
  - chmod 600 $SSH_PRIVATE_KEY
  - ssh-add $SSH_PRIVATE_KEY

deploy_staging:
  stage: deploy
  script:
    - ssh $USER@$APP_URL -o StrictHostKeyChecking=no ". restart_ssh.sh && ssh-add .ssh/id_rsa && cd app && git checkout develop && git reset --hard && git pull origin develop && docker-compose down && docker-compose -f docker-compose.prod.yml up --build -d -force--recreate && exit"
  only:
    - develop
    
