stages:
  - deploy

before_script:
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")

deploy_staging:
  stage: deploy
  script:
    - ssh ubuntu@"$APP_URL"
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$GITHUB_KEY")
    - ls
    - cd convexity-blockchain
    - git pull origin master
    - docker-compose build consumer backend
    - docker-compose up -d
    - exit
  only:
    - master
