version: "3.9"

services:
  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - web-root:/var/www/html
      - ./nginx:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - dhparam:/etc/ssl/certs
    depends_on:
      - backend
    networks:
      - gateway

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - webserver
    command: certonly --webroot --webroot-path=/var/www/html --email charles@withconvexity.com --agree-tos --no-eff-email --force-renewal -d api.chats.cash

  rabbitmq:
    image: "rabbitmq:3.8.14-alpine"
    container_name: rabbitmq
    networks:
      - rabbitmq
    restart: unless-stopped

  postgres:
    image: postgres:11-alpine
    container_name: postgres
    networks:
      - postgres
    volumes:
      - postgres:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: unless-stopped

  backend:
    depends_on:
      - postgres
      - rabbitmq
    container_name: backend
    build:
      context: convexity-backend
      dockerfile: Dockerfile
    networks:
      - gateway
      - postgres
      - rabbitmq
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true

  consumer:
    depends_on:
      - postgres
      - rabbitmq
      - backend
    container_name: consumer
    build:
      context: consumer
      dockerfile: Dockerfile
    networks:
      - gateway
      - postgres
      - rabbitmq
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true

networks:
  gateway:
    driver: bridge
    name: gateway
  rabbitmq:
    internal: true
  postgres:
    internal: true

volumes:
  postgres:
    external: true
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /home/ubuntu/convexity-blockchain/views/
      o: bind
  dhparam:
    driver: local
    driver_opts:
      type: none
      device: /home/ubuntu/convexity-blockchain/dhparam/
      o: bind
