version: "3.9"

services:
  rabbitmq:
    image: "rabbitmq:3.8.14-alpine"
    container_name: rabbitmq
    networks:
      - rabbitmq
    restart: unless-stopped
    logging:
      driver: none

  backend:
    depends_on:
      - rabbitmq
      - postgres
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    volumes: 
    - ./:/app
    - /app/node_modules
    # environment:
    #   - PORT=8080
    #   - NODE_ENV=development
    env_file:
      - ./.env
    ports: 
      - 8080:8080
      - 5432:5432
    expose:
      - 8080
    networks:
      - gateway
      - rabbitmq
    restart: unless-stopped
    command: npm run start:dev
  postgres:
      image: postgres:11-alpine
      container_name: postgres
      networks:
        - postgres
      volumes:
        - postgres:/var/lib/postgresql/data
        - /etc/localtime:/etc/localtime:ro
      environment:
        - POSTGRES_DB=chats-dev
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=123456
        - POSTGRES_PORT=5432
        - POSTGRES_HOST=localhost
      restart: unless-stopped
      env_file:
      - ./.env
      

  consumer:
    depends_on:
      - rabbitmq
      - backend
    container_name: consumer
    build:
      context: .
      dockerfile: Dockerfile.Consumer
    volumes: 
    - ./:/app
    - /app/node_modules
    environment:
      - PORT=8080
      - NODE_ENV=development
    networks:
      - gateway
      - rabbitmq
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    command: npm run start:consumer:dev

networks:
  gateway:
    driver: bridge
    name: gateway
  postgres:
    external: false
  rabbitmq:
    internal: true
volumes:
  postgres:
    external: false
