version: "3.3"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: registry.gitlab.com/convexityteam/chats-api/api:latest
    container_name: backend
    volumes: 
    - /home:/app
    environment:
      - PORT=8080
      - NODE_ENV=production
    ports: 
      - 8080:8080
    expose:
      - 8080
    networks:
      - gateway
      # - postgres
      - rabbitmq
    restart: unless-stopped
    command: npm run start
    # security_opt:
      # - no-new-privileges:true

  consumer:
    depends_on:
      - backend
    build:
      context: .
      dockerfile: Dockerfile.Consumer
    image: registry.gitlab.com/convexityteam/chats-api/consumer:latest
    container_name: consumer
    volumes: 
    - /vhome:/app
    environment:
      - PORT=8080
      - NODE_ENV=production
    networks:
      - gateway
      - rabbitmq
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    command: npm run start:consumer

networks:
  gateway:
    driver: bridge

  rabbitmq:
    internal: true
