version: "3.9"

services:
  webserver:
    image: nginx:1.20.0-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - backend
    networks:
      - gateway

  rabbitmq:
    image: "rabbitmq:3.8.14-alpine"
    container_name: rabbitmq
    networks:
      - rabbitmq
    restart: unless-stopped

  postgres:
    image: postgres:11-alpine
    container_name: postgres
    networks:
      - postgres
    volumes:
      - postgres:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: unless-stopped

  backend:
    depends_on:
      - postgres
      - rabbitmq
    container_name: backend
    build:
      context: convexity-backend
      dockerfile: Dockerfile
    networks:
      - gateway
      - postgres
      - rabbitmq
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true

  consumer:
    depends_on:
      - postgres
      - rabbitmq
      - backend
    container_name: consumer
    build:
      context: consumer
      dockerfile: Dockerfile
    networks:
      - gateway
      - postgres
      - rabbitmq
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true

networks:
  gateway:
    driver: bridge
    name: gateway
  rabbitmq:
    internal: true
  postgres:
    internal: true

volumes:
  postgres:
    external: true
  certbot-etc:
    external: false
  certbot-var:
    external: false
