name: Publish Docker Image

on: 
  push: 
    branches: [ staging ]
  release:
    types:
      - published

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./Dockerfile
            image: ghcr.io/convexityteam/chatsapi
          - dockerfile: ./Dockerfile.Consumer
            image: ghcr.io/convexityteam/consumer
    permissions:
      contents: read
      packages: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # - name: Docker meta
      #   id: docker_meta
      #   uses: crazy-max/ghaction-docker-meta@v1
      #   with:
      #     images: ghcr.io/convexityteam/chatsapi
      #     tag-sha: true
      #     tag-edge: false
      #     tag-latest: true

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ matrix.image }}

      - name: Set up Qemu
        uses: docker/setup-buildx-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: $({ github.repository_owner })
          password: $({ secret.GHCR_PASSWORD})

      - name: Build image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ${{ matrix.dockerfile }} 
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Push image
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ${{ matrix.dockerfile }} 
          
  
  
